---
koha:
  container_name: koha_container
  image: "digibib/koha:${KOHA_IMAGE_TAG}"
  cap_add:
    - SYS_NICE
    - DAC_READ_SEARCH
    - MKNOD
  environment:
    KOHA_ADMINPASS: "${KOHA_ADMINPASS}"
    KOHA_ADMINUSER: "${KOHA_ADMINUSER}"
    KOHA_INSTANCE: "$KOHA_INSTANCE"
  links:
    - koha_mysql:db
  ports:
    - "6001:6001"
    - "8080:8080"
    - "8081:8081"
  volumes:
    - "/var/migration_workdir:/var/migration_workdir:rw"

koha_mysql:
  container_name: koha_mysql_container
  cap_add:
    - MKNOD
  command:
    - mysqld
    - "--datadir=/var/lib/mysql"
    - "--user=mysql"
    - "--max_allowed_packet=64M"
    - "--wait_timeout=6000"
    - "--bind-address=0.0.0.0"
  environment:
    MYSQL_DATABASE: "koha_${KOHA_INSTANCE}"
    MYSQL_PASSWORD: "${KOHA_ADMINPASS}"
    MYSQL_ROOT_PASSWORD: "${KOHA_ADMINPASS}"
    MYSQL_USER: "${KOHA_ADMINUSER}"
  image: mysql:5.6.20
  ports:
    - "3306:3306"
  volumes_from:
    - koha_mysql_data

koha_mysql_data:
  container_name: koha_mysql_data
  image: "busybox:latest"
  volumes:
    - /var/lib/mysql

elasticsearch_data:
  container_name: elasticsearch_data
  image: "busybox:latest"
  volumes:
    - /usr/share/elasticsearch/data

elasticsearch:
  container_name: elasticsearch_container
  image: elasticsearch:2.1.0
  ports:
    - "8200:9200"
    - "8300:9300"
  command: "elasticsearch --network.host _non_loopback_"
  volumes:
    - /etc/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  volumes_from:
    - elasticsearch_data

fuseki_data:
  container_name: fuseki_data
  image: "busybox:latest"
  volumes:
    - /data

fuseki:
  container_name: fuseki_container
  image: fisch42/fuseki
  ports:
    - "3030:3030"
  volumes:
    - /etc/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  volumes_from:
    - fuseki_data

sip:
  container_name: sip_proxy_container
  image: "digibib/biblio-sip2:${SIP_IMAGE_TAG}"
  ports:
    - "6002:6001"

catalinker:
  container_name: redef_catalinker_container
  image: "digibib/redef-catalinker:${KOHA_IMAGE_TAG}"
  ports:
    - "8010:8010"
  environment:
    KOHA_OPAC_PORT: "http://${HOST}:8080"
    KOHA_INTRA_PORT: "http://${HOST}:8081"
    SERVICES_PORT: "http://${HOST}:8005"

services:
  container_name: redef_services_container
  image: "digibib/redef-services:${KOHA_IMAGE_TAG}"
  ports:
    - "8005:8005"
    - "8006:8006"
    - "5700:5700"
  environment:
    KOHA_USER: "${KOHA_ADMINUSER}"
    KOHA_PASSWORD: "${KOHA_ADMINPASS}"
    KOHA_PORT: "http://${HOST}:8081"
    TRIPLESTORE_PORT: "http://${HOST}:${TRIPLESTORE_PORT}"
    DATA_BASEURI: "${DATA_BASEURI}"
    ELASTICSEARCH_URL: "http://${HOST}:${ELASTICSEARCH_PORT}"

patron-client:
  container_name: redef_patron_client_container
  image: "digibib/redef-patron-client:${KOHA_IMAGE_TAG}"
  ports:
    - "8000:8000"
  environment:
    SERVICES_PORT: "http://${HOST}:${SERVICES_PORT}"

overview:
  container_name: overview_container
  image: connexiolabs/alpine-nginx:1.7.11
  ports:
    - "${OVERVIEW_PORT}:${OVERVIEW_PORT}"
  volumes:
    - /var/www/overview:/etc/nginx/html
