---
version: '2.1'

services:
  koha:
    logging:
      driver: "journald"

  koha_mysql:
    command:
      - mysqld
      - "--datadir=/var/lib/mysql"
      - "--user=mysql"
      - "--max_allowed_packet=64M"
      - "--wait_timeout=6000"
      - "--bind-address=0.0.0.0"
      - "--innodb-buffer-pool-size=16G"
      - "--max-connections=500"
      - "--innodb-flush-method=O_DIRECT"
      - "--skip-name-resolve"
    logging:
      driver: "journald"

  services:
    logging:
      driver: "journald"

  catalinker:
    logging:
      driver: "journald"

  patron_client:
    logging:
      driver: "journald"

  rfidhub:
    logging:
      driver: "journald"

  mail:
    environment:
      FORWARD_SMTP: "${FORWARD_SMTP}"
    logging:
      driver: "journald"

  sms:
    environment:
      FORWARD_SMS: "${FORWARD_SMS}"
    logging:
      driver: "journald"

  elasticsearch:
    logging:
      driver: "journald"

  fuseki:
    logging:
      driver: "journald"

  tagvision_sip_proxy:
    container_name: tagvision_sip_proxy
    image: "digibib/sip2proxy:c83305db07f0567971229aefcb76d222509b4fef"
    ports:
      - "6002:9999"
    command:
      - "/sip2proxy"
      - "-from=:9999"
      - "-to=xkoha:${SIP_PORT:-6001}"
      - "-log-messages=true"
      - "-replace-10=true"
      - "-log-metrics-every-s=300"
      - "-ensure-branch=true"
      - "-gelf=udp://10.172.2.16:12201"
      - "-extended-id=true"
    logging:
      driver: "journald"

  sip_proxy:
    container_name: sip_proxy
    image: "digibib/sip2proxy:c83305db07f0567971229aefcb76d222509b4fef"
    command:
      - "/sip2proxy"
      - "-from=:9999"
      - "-to=xkoha:${SIP_PORT:-6001}"
      - "-log-messages=true"
      - "-replace-10=true"
      - "-log-metrics-every-s=300"
      - "-ensure-branch=true"
      - "-gelf=udp://10.172.2.16:12201"
      - "-extended-id=false"
    logging:
      driver: "journald"

  overview:
    logging:
      driver: "journald"